---

- name: Install acpid
  yum:
    name: "{{ acpid_package }}"
    state: present


- name: Install acpid_extra_packages
  yum:
    name: "{{ acpid_extra_packages }}"
    state: present

- name: Create /etc/sysconfig/acpid
  template:
    src: RedHat.sysconfig.j2
    dest: /etc/sysconfig/acpid
    validate: sh -n %s
  notify: Restart acpid

- name: Enable acpid
  service:
    name: "{{ acpid_service }}"
    enabled: true
