---
# tasks file for ansible-role-acpid

- name: "Include variables {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create acpid_events files
  template:
    src: event.j2
    dest: "{{ acpid_events_dir }}/{{ item.name }}"
    validate: sh -n %s
  with_items: "{{ acpid_events }}"
  when:
    - "not 'state' in item or ('state' in item and item.state == 'present')"
  notify: Restart acpid

- name: Remove acpid_events files
  file:
    path: "{{ acpid_events_dir }}/{{ item.name }}"
    state: absent
  with_items: "{{ acpid_events }}"
  when:
    - "'state' in item and item.state == 'absent'"
  notify: Restart acpid

- name: Start acpid
  service:
    name: "{{ acpid_service }}"
    state: started
